DELETE FROM [dbo].[EmployeeTerritories]
DELETE FROM [dbo].[Territories]
DELETE FROM [dbo].[Region]
DELETE FROM [dbo].[Order Details]
DELETE FROM [dbo].[Orders]
DELETE FROM [dbo].[Employees]
DELETE FROM [dbo].[Products]
DELETE FROM [dbo].[Categories]
DELETE FROM [dbo].[Shippers]
DELETE FROM [dbo].[Suppliers]
DELETE FROM [dbo].[Customers]
